### ISSUE TITLE
Bug in box intersection

### ISSUE THREAD

**Issue by Sarimuko** [IBM/adversarial-robustness-toolbox#173]
Hi,

I'm trying to reuse some code in decision_verification, and have found a bug in box intersection.
In the original code, when `lower_bound > upper_bound`, intervals in a box are cleared, which denotes that there is no restriction in the box, and which is not reasonable. 
when `lower_bound > upper_bound`, the intervals should be modified to [lower_bound, lower_bound] or [upper_bound, upper_bound] instead.

**Comment by beat-buesser** [comment]
Hi @Sarimuko Thank you for using ART and raising this issue and please apologise the delayed response. We will take a look at your proposal as soon as possible this week.

**Comment by beat-buesser** [comment]
Hi @Sarimuko Are you referring to line https://github.com/IBM/adversarial-robustness-toolbox/blob/b58a890a8304186422ffd79b845f9dfd8912d7ba/art/metrics/verification_decisions_trees.py#L394

This line is intended to clear the intervals for cases of `lower_bound >= upper_bound`.

Could you please provide more details or an example script?

**Comment by Sarimuko** [comment]
For example, when two boxes with intervals {1: [-inf, 3]} and {1:[4, inf]} are intersected, the result box should contain nothing with restrictions{1: [3,3]} or {1:[4,4]}.
If the intervals are cleared, the result box will allow all data points to fall into it, which seems to make no sense.

**Comment by beat-buesser** [comment]
In our implementation`intervals` is a dictionary which contains the valid ranges for all features involved in the decisions leading to a leaf node. Features that are not required to reach a leaf node are not in the intervals dictionary. Initially, all leaf nodes extracted from a trained classifier have by definition non-empty intervals/dictionaries, otherwise there would be not decision tree. During searching for minimal perturbations, an intersection of two boxes can lead to a feature with an empty interval and therefore a box that has no volume or is empty. In that case our implementation clears the interval dictionary to represent this empty box. That way we only have to check if the dictionary is not empty to know if we have to consider it during search. In your example one would still have to loop over all features and check for each feature if `lower_bound == upper_bound` introducing numerical issues or use a special key representing empty boxes, but in Python checking for an empty dictionary is the easiest solution.

You have mentioned `decision_verification`, what is it or what are you working on?

**Comment by Sarimuko** [comment]
Got it and thanks for the explanation.
I think I misunderstood the definition of Box before.

**Comment by beat-buesser** [comment]
No worries, and please let us know once you have code that is ready to become a new feature of ART.
