### ISSUE TITLE
Randomised Smoothing as Training or Certification

### ISSUE THREAD

**Issue by beat-buesser** [IBM/adversarial-robustness-toolbox#295]
Investigate if Randomised Smoothing can be added as an adversarial trainer or if we should create a separate API for certifications.

**Comment by davidslater** [comment]
From my understanding of randomized smoothing methods (and I recent discussion I had with JHU folks), the training part is relatively straightforward. It is just a basic data augmentation technique there.

The challenge, in terms of API, is at inference time. There, we would need to perform inference on a large number of (sampled) perturbed images and average over them. Determining gradients would be non-trivial, as the output is stochastic, so you'll need to do some form of EoT.

**Comment by mathsinn** [comment]
@davidslater We already have randomized smoothing in ART, as a classifier wrapper: https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/wrappers/randomized_smoothing.py
It implements, in the `.predict` function, the sampling-based logic that you described.

The purpose of this issue here is to decide whether randomized smoothing should be moved under the Trainer defence API or whether we should create a new, dedicated API for certification defences. What are your thoughts on that?

Indeed, the gradients calculations aren't trivial. This paper describes first-order methods and an end-to-end white-box attack against smoothed classifiers: http://papers.nips.cc/paper/9307-provably-robust-deep-learning-via-adversarially-trained-smoothed-classifiers.pdf

**Comment by davidslater** [comment]
Randomized smoothing doesn't technically require a special training process - it can be applied to any underlying classifier - so I don't think it fits overly well with the adversarial trainer. (Though you can use adversarial training on the underlying classifier.)

I'm not sure that a separate API for "certifications" makes sense either, as the methods to create certificates can vary quite a bit between methods.

I do like the randomized smoothing Wrapper, though I think the current approach is inconsistent: I think the `loss_gradient` and `class_gradient` methods should return the gradients of the smoothed classifier (as `predict` does), not the underlying gradients.

Perhaps a specific API for smoothing?

**Comment by mathsinn** [comment]
To @davidslater 's previous comment: as there is no closed-form expression for computing the loss gradients of smoothed classifiers, we could resort to the approximation in equation (6) in 
http://papers.nips.cc/paper/9307-provably-robust-deep-learning-via-adversarially-trained-smoothed-classifiers.pdf).
