### ISSUE TITLE
Base class for blackbox or graybox attacks?

### ISSUE THREAD

**Issue by arashno** [IBM/adversarial-robustness-toolbox#317]
The BlackBox or GrayBox attacks are conceptually different from the WhiteBox attacks. The only existing BlackBox attack (Query-efficient black-box attack (Ilyas et al., 2017)) implementation does not extend any base class. It seems a separate base class for them could be very useful.

**Comment by beat-buesser** [comment]
Hi @arashno Thank you very much for your interest in ART!

It is not correct that there is only one black box attack, because. ART also provides in addition to Query-efficient black-box attack the Zeroth-order optimisation (ZOO), HopSkipJump, or Spatial transformation attacks as black box attacks which are extending the base class `EvasionAttack`.

Why would a separate base class be useful for you?

**Comment by arashno** [comment]
Hi @beat-buesser 
Thanks for your quick reply.
Sorry, I am new to this field and I don't know much details on different attacks.

First, I found that the Query-efficient black-box attack class does not extend any base class. 
(https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/wrappers/query_efficient_bb.py)
I expected it to use the same base class as the other attacks. Is anything is so special about this attack that couldn't be fit to any base class or I am looking at an old version of the code?

Second, I expect to see different base classes for white-box and back-box attacks because they are different by nature. Am I wrong?

**Comment by beat-buesser** [comment]
Hi @arashno 

No worries, these are good questions. Maybe we should add attack-scenario-specific base classes at some point. Let me explain why we don't have them so far.

1. I think the implementation of Query-efficient black-box as a wrapper (of a classifier) instead of an `EvasionAttack` is that it behaves like a (black-box) classifier which through (efficient) queries approximates its loss gradients and that way could also be attacked with white-box attacks.

2. Currently ART's Classifier API (https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/classifiers/classifier.py) defines if a classifier can be attack by white-box attacks if it fulfils the `ClassifierGradients` mixin abstract base class in addition to the classifier abstract base class `Classifier` which by itself is sufficient for black-box attacks. The attacks then check if the provided/attacked classifier provides the API they require.
