### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by minhhpham** [IBM/adversarial-robustness-toolbox#348]
**Describe the bug**
We were trying to follow the example in [examples/mnist_transferability.py](https://github.com/IBM/adversarial-robustness-toolbox/blob/master/examples/mnist_transferability.py). We used the exact same data set (MNIST) to train the same Keras model. The code file is provided [here](https://gist.github.com/minhhpham/7ed9b4f43f536cb60412a372d9f09c28#file-cifar_seed-py) and the model file is [here](https://drive.google.com/file/d/0B8DLrkgE3tHcR0xxakRZUm11alVnZVJab2hOR1pUZWZwTHNF/view?usp=sharing). Everything works so far.

Then, we repeatedly generate adversarial data by using PGD and CW inside a for loop (31 iterations. After about 5 iterations, the program was killed by the Operating System because memory usage keeps rising (we have 45 GB of RAM available before running the code).

I tried to do garbage collection but that didn't help. I printed out the size of all objects in `locals()` (line 44 of the code) and observed that none of them increases RAM Usage after each iteration. So I think there may be memory leak in the ART library.

I'm tagging @jinglin80 for follow ups.

**To Reproduce**
1. Download the model file [here](https://drive.google.com/file/d/0B8DLrkgE3tHcR0xxakRZUm11alVnZVJab2hOR1pUZWZwTHNF/view?usp=sharing)
2. Download the code [here](https://gist.github.com/minhhpham/7ed9b4f43f536cb60412a372d9f09c28#file-cifar_seed-py)
3. Execute the code in the same directory as the model file `python3 cifar_seed.py`

**Expected behavior**
RAM Usage keeps increasing until the Operating System kills the program

**System information (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Python version: 3.7.6
 - ART version or commit number: 1.1.1
 - TensorFlow 2.0.0

**Comment by beat-buesser** [comment]
Hi @minhhpham Thank you very much for using ART and raising this issue! We will investigate it as soon as possible.

**Comment by beat-buesser** [comment]
Hi @minhhpham and @jinlin80,
I have made a few test runs with your script and model. I was able to see a quite dramatic increase in memory usage from the beginning during the iterations with `attack_cw` (Carlini&Wagner) using TensorFlow 2.0.0 as reported by you above. This increase completely disappears if I upgrade to TensorFlow 2.1.0 as recommended, therefore I think this memory leak is caused by TensorFlow 2.0.0 and not by ART, which is also support by multiple related issues e.g. https://github.com/tensorflow/tensorflow/issues/33030.
