### ISSUE TITLE
Error changing HopSkipJump to Zoo attack on blackbox tesseract ocr

### ISSUE THREAD

**Issue by CarlosMoralesSal** [IBM/adversarial-robustness-toolbox#379]
**Describe the bug**
On this notebook: https://github.com/IBM/adversarial-robustness-toolbox/blob/master/notebooks/classifier_blackbox_tesseract.ipynb, a mate and me are working on this and when we try to change the attack to Zoo from the HopSkipJump we have an error: 
AttributeError: 'BlackBoxClassifier' object has no attribute 'channel_index'

**To Reproduce**
We just change this line attack = HopSkipJump(classifier=classifier, targeted=True, norm=2, max_iter=0, max_eval=1000, init_eval=10) and we put Zoo instead of HopSkipJump and we see the error we showed before.

**Expected behavior**
As we see Zoo is imported, we think just changing this word, it would be enough.

**Comment by beat-buesser** [comment]
Hi @CarlosMoralesSal Thank you for raising this issue. I don't think this is an actual error, it's caused because not all attacks can be combined with all classifiers. We are working on better warnings in such cases for ART 1.3 using the new exception `EstimatorError`. In this case `ZooAttack` requires the property `channel_index` which is not provided by `BlackBoxClassifier`.
