### ISSUE TITLE
Question about using HopSkipJump and BlackboxClassifer for Tesseract

### ISSUE THREAD

**Issue by CarlosMoralesSal** [IBM/adversarial-robustness-toolbox#380]
**Describe the bug**
We have test two images with the tesseract directly and both images have been recognized and we have found the numbers correctly, but once we test them with this notebook: attack = HopSkipJump(classifier=classifier, targeted=True, norm=2, max_iter=0, max_eval=1000, init_eval=10), one of the images it is not recognized, as well, once the HopSkipJump is working, when we should see the images as in the example, we just see a white box with a red spot on it.

**To Reproduce**
We put our images that we attach on this issue and we start the normal flow of the notebook. They are normal images as you can see. They are normal jpg files and as well we have tested with png files.

**Expected behavior**
We expect to see the attack on our images as on the example and see the error level on the example
![25](https://user-images.githubusercontent.com/13416037/79668921-6794ec00-81b8-11ea-9135-7cbe09b15f6f.jpg)
![85](https://user-images.githubusercontent.com/13416037/79668928-6bc10980-81b8-11ea-81a6-723b79262c27.jpg)

**Comment by beat-buesser** [comment]
Hi @CarlosMoralesSal Thank you for raising this issue. It could probably depend on how you are loading an preprocessing these images. Could you please share the fill code you are using?

**Comment by CarlosMoralesSal** [comment]
Of course, it is the same as in the example, just changing the images. Thanks

**Comment by beat-buesser** [comment]
Could you please share your notebook, just to be sure and avoid confusion on our side?

**Comment by CarlosMoralesSal** [comment]
Yes, here you have 
[tessearact_notebook.zip](https://github.com/IBM/adversarial-robustness-toolbox/files/4497482/tessearact_notebook.zip)

Thanks

**Comment by beat-buesser** [comment]
Thank you very much, the file makes it easier to understand the question correctly. I think the reason for the white boxes that you have observed and described as part of the output are caused by running `matplotlib.pyplot.imshow` with an image array with a `dtype` of `np.float32` and a min/max pixel range of 47 to 180 for image 85.jpg. If I use `plt.imshow(x_adv[0].astype(np.uint8))` or `plt.imshow(x_adv[0]/255)` the images are shown as expected.

I think our notebook works with `imshow` because its images have a min-max pixel range of 0 to 255, but I'm not completely sure. We'll update the calls to `imshow` as described above in our next release and also remove the redundant import of `ZooAttack`.
