### ISSUE TITLE
Default values of some preprocessors may confuse users.

### ISSUE THREAD

**Issue by tagomaru** [IBM/adversarial-robustness-toolbox#434]
**Is your feature request related to a problem? Please describe.**
Default values of `applied_fit` and `applied_predict` of classes under `art.defences.preprocessor` do not seem to be consistent.
This may make users confused. In fact, I was confused when I was testing `FeatureSqueezing`, `GaussianAugmentation`, and `SpatialSmoothing` since only the default value of `apply_predict` of `GaussianAugmentation` is False, whereas those of the other two are True.
It took several hours to notice why `preprocessing_defences` of classifer did not affect the result of prediction.

I think these classes may need to be consistent w.r.t default values.

**Describe the solution you'd like**
According to my investigation, the default values of `applied_fit` and `applied_predict` for each class under `art.defences.preprocessor` are different as following.

|                      | apply_fit | apply_predict |
|----------------------|-----------|---------------|
| FeatureSqueezing     | False     | True          |
| GaussianAugmentation | True      | False         |
| JpegCompression      | True      | False         |
| LabelSmoothing       | True      | False         |
| PixelDefend          | False     | True          |
| SpatialSmoothing     | False     | True          |
| ThermometerEncoding  | True      | True          |
| TotalVarMin          | False     | True          |

I think it makes sense if all of `apply_fit` is False and `apply_predict` is True since I think these defense techniques are for preprocess and these should be applied before prediction.

What do you think?

**Comment by beat-buesser** [comment]
Hi @tagomaru Thank you very much for raising this question and summarising the data!

The default values don't have to be consistent, because they are set to the most effective values according to the results and algorithms reported in the cited papers.

First, there is a small bug in the default values for `JpegCompression` in ART 1.2 that is being fixed in ART 1.3, there the default setting should be `apply_predict=True` and `apply_fit=True` following Fig. 3 of https://arxiv.org/pdf/1705.02900.pdf. This is being fixed by @hesseltuinhof .

A few examples:

'LabelSmoothing' is a technique that is applied only at training time to train a model on smooth labels, therefore `apply_fit=True` is required, but I think it is never really applied at predict time, therefore `apply_predict=False`.

For `GaussianAugmentation` I think the initial idea was that training a model on a mixture of original samples and samples augmented with Gaussian noise would make the model less sensitive against images with adversarial perturbations (but without added Gaussian noise) at predict time, therefore `apply_fit=True` and `apply_predict=False`. Of course `apply_predict=True` could also make sense.

For `SpatialSmoothing` we are following https://arxiv.org/pdf/1704.01155.pdf where we think this defence has only been applied at predict time, therefore `apply_fit=False` and `apply_predict=True`.

In many cases other combinations also make sense and by making them parameters we give the user the ability to set these parameters as needed for their experiments.

Do you think there might be a better way of documenting this so that other users won't get confused?

**Comment by tagomaru** [comment]
Hi @beat-buesser 
>For GaussianAugmentation I think the initial idea was that training a model on a mixture of original samples and samples augmented with Gaussian noise would make the model less sensitive against images with adversarial perturbations

Thank you for your explanation.
I understood that the value of those flags are determined by the original purposes noted on papers on which those techniques were proposed.
It definitely makes sense.

I am going to close this question.
