### ISSUE TITLE
Compatibility of defence JpegCompression with classifier's preprocessing (standardisation)

### ISSUE THREAD

**Issue by beat-buesser** [IBM/adversarial-robustness-toolbox#84]
**Is your feature request related to a problem? Please describe.**
- In classifer.predict we are applying the classifier's preprocessing before applying the defences.
- Most of the common classifier preprocessing values for standardisation result in pixel values outside of [0, 1].
- The defence `JpegCompression` expects inputs `x` to be in the range [0, 1] and clips inputs `x` to this range [0, 1].
- This can very likely result in unexpected behaviour of the classifier without any warnings.

**Describe the solution you'd like**
Are there any reasons against reversing the order to first applying the defences and then applying the preprocessing (standardisation) in classifier.predict()?
For example are there other defences that need to run after preprocessing (standardisation)?

**Describe alternatives you've considered**
- As alternative we could use the classifier's clip_values in JpegCompression to adapt the clipping for the compression step instead of just assuming [0, 1] for `x`.
- We could reverse the standardisation in `JpegCompression` and reapply it after the compression step, but this would result in extra computing efforts.
- At least we should print a warning if `JpegCompression` clips values in the input `x` that are outside of the expected range.

**Additional context**
The behaviour of `JpegCompression` is documented in its docstring.

**Comment by beat-buesser** [comment]
@ririnicolae @mathsinn What do you think?

**Comment by ririnicolae** [comment]
A few of the defenses were implemented for the [0, 1] range for simplicity or because that's how the authors were doing it. Ideally, these should be generalized to any range. We've already done this for some of them.

Also, I think there is a strong reason to not do normalization after the defenses, as it would remove the effect of some of the defenses. Moreover, it would not really solve the problem for `JpegCompression`, as the normalization range is general and can be different from [0, 1].

I can look into ways to generalize the range for `JpegCompression` if that works for you? Will have a chat with @minhitbk as well, as he implemented it to begin with. I also agree that in the case where generalization is not possible, there should be a warning when the data ranges between the defense and the classifier do not match.

**Comment by beat-buesser** [comment]
@ririnicolae Thank you, this is very helpful.

We are doing some performance testing experiments on the defence strengths that have revealed this issue, because of that we have comprehensive testing cases in place and have already implemented some fixes for this issue that we can share soon. Therefore I think I'm close to a working solution. But it would be great if we could ask you for a review later this or early next week?

We also need to consider that the defences are provided in a sequence. So even if a defence could run before standardisation, it could be positioned in the list of defences after a defence that requires standardised inputs.

**Comment by ririnicolae** [comment]
@beat-buesser Sure, feel free to assign PR reviews to me whenever you need.

Yes, because the defenses can be in any order in the list, I'm thinking the best is to have all of them be able to run on any input ranges (to the extent where it's feasible), that would cover the most general case. Looking forward to the PR. :)

**Comment by minhitbk** [comment]
The reason we need clip_values=(0, 1) for JpegCompression is that we need to convert x to the range (0, 255) for doing compression. I think its not hard to generalize clip_values to any range given that we open one more parameter input to the init function for passing clip_values.
